services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    # Configuração otimizada para recursos limitados
    command: >
      redis-server
      --maxmemory 30mb
      --maxmemory-policy allkeys-lru
      --save ""
      --appendonly no
      --tcp-keepalive 60
      --timeout 300
      --stop-writes-on-bgsave-error no
      --hash-max-ziplist-entries 512
      --hash-max-ziplist-value 64
      --list-max-ziplist-size -2
      --set-max-intset-entries 512
      --zset-max-ziplist-entries 128
      --zset-max-ziplist-value 64
      --loglevel warning
      --databases 1
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s  # Reduzido frequência
      timeout: 2s    # Timeout menor
      retries: 3     # Menos retries
      start_period: 5s
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 40M
        reservations:
          cpus: '0.1'
          memory: 20M
    # Otimizações de container
    sysctls:
      - net.core.somaxconn=512
    ulimits:
      memlock: -1
    restart: unless-stopped

  app-native-1:
    image: docker.io/maxsonferovante/api-payment-processor
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_TIMEOUT: 300ms
      REDIS_QUEUE_PAYMENTS_MAIN: rinha-payments-main-queue
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: 65M

  app-native-2:
    image: docker.io/maxsonferovante/api-payment-processor
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_TIMEOUT: 300ms
      REDIS_QUEUE_PAYMENTS_MAIN: rinha-payments-main-queue
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: 65M

  # Processador assíncrono de pagamentos - consome mensagens do Redis
  async-worker:
    image: docker.io/maxsonferovante/async-payment-processor:latest
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_TIMEOUT: 500ms
      REDIS_QUEUE_PAYMENTS_MAIN: rinha-payments-main-queue
      PAYMENT_PROCESSOR_DEFAULT_URL: http://payment-processor-default:8080
      PAYMENT_PROCESSOR_FALLBACK_URL: http://payment-processor-fallback:8080
      WORKER_BLOCKING_TIMEOUT: 300
      WORKER_MAX_CONCURRENT_PAYMENTS: 350
      WORKER_BATCH_SIZE: 100
      WORKER_EXECUTION_DELAY: 250
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 100M    

  nginx:
    image: nginx:alpine
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app-native-1
      - app-native-2
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 70M

networks:
  backend:
    driver: bridge
    name: backend
  payment-processor:
    external: true
