services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    # Configuração otimizada para recursos limitados mas estáveis
    command: >
      redis-server
      --maxmemory 60mb
      --maxmemory-policy allkeys-lru
      --save ""
      --appendonly no
      --tcp-keepalive 60
      --timeout 600
      --stop-writes-on-bgsave-error no
      --hash-max-ziplist-entries 512
      --hash-max-ziplist-value 64
      --list-max-ziplist-size -2
      --set-max-intset-entries 512
      --zset-max-ziplist-entries 128
      --zset-max-ziplist-value 64
      --loglevel warning
      --databases 1
      --tcp-backlog 511
      --maxclients 1000
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 60M
        reservations:
          cpus: '0.15'
          memory: 30M
    # Otimizações de container
    sysctls:
      - net.core.somaxconn=512
    ulimits:
      memlock: -1
    restart: unless-stopped

  app-native-1:
    image: docker.io/maxsonferovante/api-payment-processor
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_TIMEOUT: 600ms
      REDIS_QUEUE_PAYMENTS_MAIN: rinha-payments-main-queue
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: 65M

  app-native-2:
    image: docker.io/maxsonferovante/api-payment-processor
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_TIMEOUT: 600ms
      REDIS_QUEUE_PAYMENTS_MAIN: rinha-payments-main-queue
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: 65M

  # Processador assíncrono de pagamentos - consome mensagens do Redis
  async-worker:
    image: docker.io/maxsonferovante/async-payment-processor:latest
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_TIMEOUT: 600ms
      REDIS_QUEUE_PAYMENTS_MAIN: rinha-payments-main-queue
      PAYMENT_PROCESSOR_DEFAULT_URL: http://payment-processor-default:8080
      PAYMENT_PROCESSOR_FALLBACK_URL: http://payment-processor-fallback:8080
      WORKER_BLOCKING_TIMEOUT: 500
      WORKER_MAX_CONCURRENT_PAYMENTS: 300
      WORKER_BATCH_SIZE: 50
      WORKER_EXECUTION_DELAY: 100
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.45'
          memory: 90M

  nginx:
    image: nginx:alpine
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app-native-1
      - app-native-2
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 70M

networks:
  backend:
    driver: bridge
    name: backend
  payment-processor:
    external: true
